import bcrypt from 'bcryptjs'

const data = {
    users: [
      {
        name: 'Nguyễn Thành Đạt',
        username:'ntdat',
        password: bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'male',
        image: '/user/ntdat.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Lê Phương Nhi',
        username:'lpnhi',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'female',
        image: '/user/lpnhi.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Nguyễn Di Đan',
        username:'nddan',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'girl',
        image: '/user/nddan.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Tô Thị Hậu Phương',
        username:'tthphuong',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'girl',
        image: '/user/tthphuong.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Nông Bảo Khanh',
        username:'nbkhanh',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'girl',
        image: '/user/nbkhanh.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Phạm Xuân Lâm',
        username:'pxlam',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'girl',
        image: '/user/pxlam.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Lê Đức Trung',
        username:'ldtrung',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'girl',
        image: '/user/ldtrung.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Lê Thị Linh',
        username:bcrypt.hashSync('123456'),
        password:'123456',
        type: 'admin',
        gender: 'girl',
        image: '/user/ltlinh.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Lương Ngọc Đức',
        username:'lnduc',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'girl',
        image: '/user/lnduc.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Nguyễn Trần Nhật Anh',
        username:'ntnanh',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'girl',
        image: '/user/ntnanh.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Nguyễn Thị Trang',
        username:'nttrang',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'girl',
        image: '/user/nttrang.jpg',
        description: 'A popular shirt',
      },
      {
        name: 'Vũ Duy Hưng',
        username:'vdhung',
        password:bcrypt.hashSync('123456'),
        type: 'admin',
        gender: 'girl',
        image: '/user/vdhung.jpg',
        description: 'A popular shirt',
      },
    ],
  };
  
  export default data;